blog/urls.py
from . import views
from django.urls import path


app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='list_post'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

hopops/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_profile/', include('user_profile.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += path('', include('portfolio.urls')),

portfolio/urls.py
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from rest_framework import routers

from . import views

app_name = 'portfolio'

router = routers.DefaultRouter()
router.register(r'pictures', views.pictures, 'pictures')


urlpatterns = [
    path('list', views.list.as_view(), name="list"),
    path('gallery', views.gallery, name="gallery"),
    path('galleryv2', views.galleryv2, name="galleryv2"),
    path('mygallery', views.mygallery, name="mygallery"),
    path('<int:pk>', views.picture.as_view(), name="picture"),
    path('carousel/<int:picture_id>', views.carousel, name="carousel"),
    path('carouselv2/<int:picture_id>', views.carouselv2, name="carouselv2"),
    path('upload_image', views.upload_picture, name="upload_image"),
    path('test', views.get_photo, name="get_photo"),
 #   path('api/all_picture', views.all_picture, name="api_all_picture"),
    path('api/', include(router.urls)),
    path('', views.index, name="index"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static('/', document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from django.conf import settings

from . import views

app_name = 'user_profile'

urlpatterns = [
    path('register', views.register, name="register"),
    path('logout', views.logout_user, name="logout"),
    path('login', views.login_user, name="login"),
    path('edit_user', views.edit_user, name="edit_user"),
]

portfolio/models.py
from django.db import models

from django.contrib.auth.models import User

import os
from datetime import datetime
from django_resized import ResizedImageField

# Create your models here.


def photo_path(instance, filename):
    basefilename, file_extension=os.path.splitext(filename)
    now = datetime.now()
    strdate = now.strftime("%d-%m-%y-%f")
    return 'gallery/{username}/{strdate}{ext}'.format(username=instance.user.username, strdate=strdate, ext=file_extension)


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    public = models.BooleanField

    def __str__(self):
        return self.name


class Picture(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    pub_date = models.DateTimeField(auto_now_add=True)
    photo = ResizedImageField(size=[1920, 1080], upload_to=photo_path)
    public = models.BooleanField(default=False)

portfolio/forms.py
from django import forms
from .models import Category


# LIST CATEGORIES (iterable)
def get_available_categories():
    categories = ()
    for item in Category.objects.all():
        categories = categories + (((item.name), (item.name)),)
    return categories


class UpdatePicture(forms.Form):
    name = forms.CharField(label='Name', max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Name'}))
    category = forms.ChoiceField(choices=get_available_categories())
    description = forms.CharField(label='Description', max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Description'}))
    photo = forms.ImageField()
    # public = forms.BooleanField()

portfolio/views.py
from django.shortcuts import render, HttpResponse, redirect, HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, HttpResponseNotFound, request, response, JsonResponse
from django.views import generic, View
from django.core.exceptions import ViewDoesNotExist
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from json import dumps
from rest_framework import serializers

from user_profile.models import Profile
from django.contrib.auth.models import User
from .models import Picture, Category
from .forms import UpdatePicture

# Rest
from rest_framework import viewsets
from .serializers import PictureSerializer, CategorySerializer
# Create your views here.


class picture(generic.DetailView):
    model = Picture
    template_name = 'portfolio/picture.html'


class list(generic.ListView):
    template_name = 'portfolio/list.html'
    context_object_name = 'latest_picture_list'

    def get_queryset(self):
        """Return the last five published pictures."""
        return Picture.objects.all()


# def isUser(user):
#     return user.username == "staff"


# @user_passes_test(isUser, login_url="/login")
def mygallery(request):
    user = User.objects.only('id').get(username=request.user)
    all_picture = Picture.objects.filter(user=user).order_by('pub_date')
    paginator = Paginator(all_picture, 5)
    pages = request.GET.get('page', 1)
    try:
        all_picture = paginator.page(pages)
    except PageNotAnInteger:
        all_picture = paginator.page(1)
    return render(request, 'portfolio/mygallery.html', {'all_picture': all_picture})


@login_required(login_url="/user_profile/login")
def gallery(request):
    all_picture = Picture.objects.filter(public=False).order_by('pub_date')
    all_category = Category.objects.all()
    paginator = Paginator(all_picture, 5)
    pages = request.GET.get('page', 1)
    #messages.warning(request, "This page will list all the picture", extra_tags='alert')
    try:
        all_picture = paginator.page(pages)
    except PageNotAnInteger:
        all_picture = paginator.page(1)
    return render(request, 'portfolio/gallery.html', {'all_picture': all_picture, 'all_category': all_category})


@login_required(login_url="/user_profile/login")
def galleryv2(request):
    all_picture = Picture.objects.filter(public=False).order_by('pub_date')
    pix_list = [all_picture[:5], all_picture[5:]]
    all_category = Category.objects.all()
    return render(request, 'portfolio/galleryv2.html', {'all_picture': pix_list, 'all_category': all_category})


def carousel(request, picture_id):
    picture = Picture.objects.get(pk=picture_id)
    all_picture = Picture.objects.filter(public=False)[:3]
    next_picture = Picture.objects.filter(id__gt=picture_id).order_by('pk').first()
    prev_picture = Picture.objects.filter(id__lt=picture_id).order_by('pk').last()
    current_list = [picture, next_picture, prev_picture]
    context = {'picture': picture, 'all_picture': all_picture, 'next_picture': next_picture, 'prev_picture': prev_picture, 'current_list': current_list}
    return render(request, 'portfolio/carousel.html', context)


def carouselv2(request, picture_id):
    picture = Picture.objects.get(pk=picture_id)
    next_picture = Picture.objects.filter(id__gt=picture_id).order_by('pk').first()
    prev_picture = Picture.objects.filter(id__lt=picture_id).order_by('pk').last()
    current_list = [picture, next_picture, prev_picture]
    context = {'picture': picture, 'next_picture': next_picture, 'prev_picture': prev_picture, 'current_list': current_list}
    return render(request, 'portfolio/carouselv2.html', context)


def index(request):
    return render(request, "portfolio/index.html")


@login_required(login_url="/portfolio/login")
def upload_picture(request):

    if request.method == "POST":
        form = UpdatePicture(request.POST, request.FILES)

        if form.is_valid():
            user = User.objects.get(username=request.user)
            picture.user = user
            picture.name = form.cleaned_data['name']
            get_category = form.cleaned_data['category']
            picture.category = Category.objects.get(name=get_category)
            picture.description = form.cleaned_data['description']
            picture.photo = form.cleaned_data['photo']
            # picture.public = form.clean_data['public']
            # Create and Save Picture
            obj = Picture.objects.create(
                user=picture.user,
                name=picture.name,
                category=picture.category,
                description=picture.description,
                photo=picture.photo,
                public=False
            )
            obj.save()
            # Change number to Add User photo Number !
            user_profile = Profile.objects.get(user=user.id)
            user_profile.nb_photo = user_profile.nb_photo + 1
            user_profile.save()
            return HttpResponseRedirect('/portfolio/gallery')
    else:
        form = UpdatePicture()
    return render(request, "portfolio/upload_picture.html", {'form': form})


def send_dictionary(request):
    # create data dictionary
    dataDictionary = {
        'hello': 'World',
        'geeks': 'forgeeks',
        'ABC': 123,
        456: 'abc',
        14000605: 1,
        'list': ['geeks', 4, 'geeks'],
        'dictionary': {'you': 'can', 'send': 'anything', 3: 1}
    }
    # dump data
    dataJSON = dumps(dataDictionary)
    return render(request, 'portfolio/send_dictionary.html', {'data': dataJSON})


# def get_photo(request, picture_id):
def get_photo(request):
    # create data dictionary
    # picture = Picture.objects.get(pk=picture_id)
    all_picture = Picture.objects.filter(public=False)[:10]
    data = serializers.Serializer('json', all_picture)

    # dataJSON = MedicSerializer(all_picture, many=True)
    return render(request, 'portfolio/carouselv2.html', {'data': data})


# def all_picture(request):
#     all_picture = list(Picture.objects.values())
#     return JsonResponse(all_picture, safe=False)


class pictures(viewsets.ModelViewSet):
    serializer_class = PictureSerializer
    queryset = Picture.objects.all()

portfolio/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <title>{% block title %}{% endblock title %}</title>
</head>
<body>

<!-- Bootstrap -->
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

<header>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top nav">

  <div class="collapse navbar-collapse" id="navbarsExampleDefault">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:index' %}">Blog</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:gallery' %}">Gallery</a>
      </li>
      </ul>
      {% if user.is_authenticated %}
      <form class="form-inline my-2 my-lg-0">
          <a class="btn btn-secondary my-2 my-sm-0" href="{% url 'portfolio:upload_image' %}" >Upload</a>
      </form>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_username }}</a>
        <div class="dropdown-menu" aria-labelledby="dropdown01">
          {% if request.user.is_staff %}
            <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'portfolio:mygallery' %}">My Gallery</a>
          <a class="dropdown-item" href="{% url 'portfolio:edit_user' %}">Edit Profile</a>
          <a class="dropdown-item" href="{% url 'portfolio:logout' %}">Logout</a>
        </div>
      </li>
      {% else %}
    <form class="form-inline my-2 my-lg-0">
      <a class="btn btn-secondary my-2 my-sm-0" href="{% url 'portfolio:login' %}" >Login</a>
    </form>
    {% endif %}
  </div>
</nav>
</header>



<div class="mt-5 wrap">
  {% if messages %}
    <ul class="messages">
        {% for msg in messages %}
        <li>
            <div class="alert alert-success" role="alert">
            {{msg.message}}
            </div>
        </li>
        {% endfor %}
    </ul>
  {% endif %}

  {% block content %}

  {% endblock content %}
  </div>


</body>

</html>