blog/urls.py
from . import views
from django.urls import path


app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='list_post'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

hopops/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_profile/', include('user_profile.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += path('', include('portfolio.urls')),

portfolio/urls.py
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from rest_framework import routers

from . import views

app_name = 'portfolio'

router = routers.DefaultRouter()
router.register(r'pictures', views.pictures, 'pictures')


urlpatterns = [
    path('list', views.list.as_view(), name="list"),
    path('gallery', views.gallery, name="gallery"),
    path('galleryv2', views.galleryv2, name="galleryv2"),
    path('mygallery', views.mygallery, name="mygallery"),
    path('<int:pk>', views.picture.as_view(), name="picture"),
    path('carousel/<int:picture_id>', views.carousel, name="carousel"),
    path('carouselv2/<int:picture_id>', views.carouselv2, name="carouselv2"),
    path('upload_image', views.upload_picture, name="upload_image"),
    path('test', views.get_photo, name="get_photo"),
 #   path('api/all_picture', views.all_picture, name="api_all_picture"),
    path('api/', include(router.urls)),
    path('', views.index, name="index"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static('/', document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models

from django.contrib.auth.models import User

import os
from datetime import datetime
from django_resized import ResizedImageField

# Create your models here.


def photo_path(instance, filename):
    basefilename, file_extension=os.path.splitext(filename)
    now = datetime.now()
    strdate = now.strftime("%d-%m-%y-%f")
    return 'gallery/{username}/{strdate}{ext}'.format(username=instance.user.username, strdate=strdate, ext=file_extension)


class Category(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=20)
    public = models.BooleanField

    def __str__(self):
        return self.name


class Picture(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    description = models.CharField(max_length=1000)
    pub_date = models.DateTimeField(auto_now_add=True)
    photo = ResizedImageField(size=[1920, 1080], upload_to=photo_path)
    public = models.BooleanField(default=False)

portfolio/forms.py
from django import forms
from .models import Category


# LIST CATEGORIES (iterable)
def get_available_categories():
    categories = ()
    for item in Category.objects.all():
        categories = categories + (((item.name), (item.name)),)
    return categories


class UpdatePicture(forms.Form):
    name = forms.CharField(label='Name', max_length=20, widget=forms.TextInput(attrs={'placeholder': 'Name'}))
    category = forms.ChoiceField(choices=get_available_categories())
    description = forms.CharField(label='Description', max_length=50, widget=forms.TextInput(attrs={'placeholder': 'Description'}))
    photo = forms.ImageField()
    # public = forms.BooleanField()

blog/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
from .models import Post


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/list_blog.html'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

portfolio/views.py
from django.shortcuts import render, HttpResponse, redirect, HttpResponseRedirect
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse, HttpResponseNotFound, request, response, JsonResponse
from django.views import generic, View
from django.core.exceptions import ViewDoesNotExist
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger
from django.contrib.auth import authenticate, logout, login
from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from json import dumps
from rest_framework import serializers

from user_profile.models import Profile
from django.contrib.auth.models import User
from .models import Picture, Category
from .forms import UpdatePicture

# Rest
from rest_framework import viewsets
from .serializers import PictureSerializer, CategorySerializer
# Create your views here.


class picture(generic.DetailView):
    model = Picture
    template_name = 'portfolio/picture.html'


class list(generic.ListView):
    template_name = 'portfolio/list.html'
    context_object_name = 'latest_picture_list'

    def get_queryset(self):
        """Return the last five published pictures."""
        return Picture.objects.all()


# def isUser(user):
#     return user.username == "staff"


# @user_passes_test(isUser, login_url="/login")
def mygallery(request):
    user = User.objects.only('id').get(username=request.user)
    all_picture = Picture.objects.filter(user=user).order_by('pub_date')
    paginator = Paginator(all_picture, 5)
    pages = request.GET.get('page', 1)
    try:
        all_picture = paginator.page(pages)
    except PageNotAnInteger:
        all_picture = paginator.page(1)
    return render(request, 'portfolio/mygallery.html', {'all_picture': all_picture})


@login_required(login_url="/user_profile/login")
def gallery(request):
    all_picture = Picture.objects.filter(public=False).order_by('pub_date')
    all_category = Category.objects.all()
    paginator = Paginator(all_picture, 5)
    pages = request.GET.get('page', 1)
    #messages.warning(request, "This page will list all the picture", extra_tags='alert')
    try:
        all_picture = paginator.page(pages)
    except PageNotAnInteger:
        all_picture = paginator.page(1)
    return render(request, 'portfolio/gallery.html', {'all_picture': all_picture, 'all_category': all_category})


@login_required(login_url="/user_profile/login")
def galleryv2(request):
    all_picture = Picture.objects.filter(public=False).order_by('pub_date')
    pix_list = [all_picture[:5], all_picture[5:]]
    all_category = Category.objects.all()
    return render(request, 'portfolio/galleryv2.html', {'all_picture': pix_list, 'all_category': all_category})


def carousel(request, picture_id):
    picture = Picture.objects.get(pk=picture_id)
    all_picture = Picture.objects.filter(public=False)[:3]
    next_picture = Picture.objects.filter(id__gt=picture_id).order_by('pk').first()
    prev_picture = Picture.objects.filter(id__lt=picture_id).order_by('pk').last()
    current_list = [picture, next_picture, prev_picture]
    context = {'picture': picture, 'all_picture': all_picture, 'next_picture': next_picture, 'prev_picture': prev_picture, 'current_list': current_list}
    return render(request, 'portfolio/carousel.html', context)


def carouselv2(request, picture_id):
    picture = Picture.objects.get(pk=picture_id)
    next_picture = Picture.objects.filter(id__gt=picture_id).order_by('pk').first()
    prev_picture = Picture.objects.filter(id__lt=picture_id).order_by('pk').last()
    current_list = [picture, next_picture, prev_picture]
    context = {'picture': picture, 'next_picture': next_picture, 'prev_picture': prev_picture, 'current_list': current_list}
    return render(request, 'portfolio/carouselv2.html', context)


def index(request):
    return render(request, "portfolio/index.html")


@login_required(login_url="/portfolio/login")
def upload_picture(request):

    if request.method == "POST":
        form = UpdatePicture(request.POST, request.FILES)

        if form.is_valid():
            user = User.objects.get(username=request.user)
            picture.user = user
            picture.name = form.cleaned_data['name']
            get_category = form.cleaned_data['category']
            picture.category = Category.objects.get(name=get_category)
            picture.description = form.cleaned_data['description']
            picture.photo = form.cleaned_data['photo']
            # picture.public = form.clean_data['public']
            # Create and Save Picture
            obj = Picture.objects.create(
                user=picture.user,
                name=picture.name,
                category=picture.category,
                description=picture.description,
                photo=picture.photo,
                public=False
            )
            obj.save()
            # Change number to Add User photo Number !
            user_profile = Profile.objects.get(user=user.id)
            user_profile.nb_photo = user_profile.nb_photo + 1
            user_profile.save()
            return HttpResponseRedirect('/portfolio/gallery')
    else:
        form = UpdatePicture()
    return render(request, "portfolio/upload_picture.html", {'form': form})


def send_dictionary(request):
    # create data dictionary
    dataDictionary = {
        'hello': 'World',
        'geeks': 'forgeeks',
        'ABC': 123,
        456: 'abc',
        14000605: 1,
        'list': ['geeks', 4, 'geeks'],
        'dictionary': {'you': 'can', 'send': 'anything', 3: 1}
    }
    # dump data
    dataJSON = dumps(dataDictionary)
    return render(request, 'portfolio/send_dictionary.html', {'data': dataJSON})


# def get_photo(request, picture_id):
def get_photo(request):
    # create data dictionary
    # picture = Picture.objects.get(pk=picture_id)
    all_picture = Picture.objects.filter(public=False)[:10]
    data = serializers.Serializer('json', all_picture)

    # dataJSON = MedicSerializer(all_picture, many=True)
    return render(request, 'portfolio/carouselv2.html', {'data': data})


# def all_picture(request):
#     all_picture = list(Picture.objects.values())
#     return JsonResponse(all_picture, safe=False)


class pictures(viewsets.ModelViewSet):
    serializer_class = PictureSerializer
    queryset = Picture.objects.all()

templates/portfolio/blog.html
{% extends "base.html" %}
{% block title %}Register{% endblock title %}

{% block content %}
<main class="main">




</main>
{% endblock content %}

templates/portfolio/carousel.html
{% extends "base.html" %}
{% block title %}Carousel{% endblock title %}

{% block content %}

<div class="p-5 image-border container-fluid" align="center">
    <div class="row">
        <div class="carousel-inner ">
        {% for picture in current_list|slice:":3" %}
            {% if forloop.first %}
                <div class="carousel-active item">
                    <img class="img-fluid rounded" src="{{ picture.photo.url }}" alt="{{ picture.name }}">
                    <div class="carousel-caption d-md-block rounded position-absolute bg-custom">
                        <h3>{{ picture.name }}</h3>
                        {% if picture.user.first_name %}
                        <p><span>©</span> {{ picture.user.first_name }} {{ picture.user.last_name }}</p>
                        {% endif %}
                    </div>
                </div>
            {% else %}
                <div class="item">
                </div>
            {% endif %}
                <!--<blockquote>
                    <p>{{ picture.name }}</p>
                </blockquote>
                <label>{{ picture.description }}</label>-->
        {% endfor %}

            {% if prev_picture %}
              <a class="carousel-control-prev " href="{{ prev_picture.id }}" data-slide="prev">
                <span class="carousel-control-prev-icon"></span>
              </a>
            {% endif %}
            {% if next_picture %}
              <a class="carousel-control-next" href="{{ next_picture.id }}" data-slide="next">
                <span class="carousel-control-next-icon"></span>
              </a>
            {% endif %}

        </div>
    </div>
</div>


{% endblock content %}

templates/portfolio/carouselv2.html
{% extends "base.html" %}
{% load static %}
{% block title %}Carousel{% endblock title %}

{% block content %}

<div class="album">

    <div class="container bg-dark">
        <div class="row p-1 m-1 ">

            <div class="col">
            {% if prev_picture %}
                <a class="carousel-control-prev" href="{{ prev_picture.id }}" data-slide="prev">
                    <span class="carousel-control-prev-icon"></span>
                </a>
            {% endif %}
            </div>




            <div class="col col-md-9">

                <div class="card mb-4 shadow">

                    <img class="card text-center" src="{{picture.photo.url}}">

                        <div class="">
                            <footer class="blockquote-footer text-center">
                            <small class="text-muted">
                            <h3>{{ picture.name }}</h3>
                            {% if picture.user.first_name %}
                                <p><span>©</span> {{ picture.user.first_name }} {{ picture.user.last_name }}</p>
                            {% endif %}
                            </small>
                            </footer>
                        </div>
                    </div>
                </div>

            <div class="col">
                {% if next_picture %}
                <a class="carousel-control-next" href="{{ next_picture.id }}" data-slide="next">
                    <span class="carousel-control-next-icon"></span>
                </a>
                {% endif %}
            </div>


            </div>

        </div>
    </div>
</div>
{% endblock content %}

templates/portfolio/gallery.html
{% extends "base.html" %}
{% block title %}Gallery{% endblock title %}

{% block content %}
<main class="main">

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Item</th>
        </tr>
    </thead>
 <!--   <tbody>
    {% for item in all_picture %}
        <tr>
            <td>{{ item.name }}</td>
        </tr>
    {% endfor %}
    </tbody>
    -->
    <div class="row">
    {% for item in all_picture %}
    <div class="col">
          <h8>{{ item.name }}</h8>
            <br/>
          <a href="{% url 'portfolio:carousel' item.id %}"><img class="img-thumbnail" src="{{ item.photo }}" alt="{{ item.name }}" width="200"></a>
    </div>

    {% endfor %}
    </div>

</table>

{% if all_picture %}
<table>
    <tr class="pagination">
        {% if all_picture.has_previous %}
            <td><a href="?page{{ all_picture.previous_page_number }}">Previous</a></td>
        {% endif %}
                <td class="">
                    <span>{{ all_picture.number }} of {{ all_picture.paginator.num_pages }}.</span>
                </td>
        {% if all_picture.has_next %}
            <td><a href="?page={{ all_picture.next_page_number }}">Next</a></td>
        {% endif %}

        </tr>
    {% endif %}
</table>

</main>

{% endblock content %}

templates/portfolio/galleryv2.html
{% extends "base.html" %}
{% block title %}Gallery{% endblock title %}

{% block content %}

<div class="row p-3">
    <div class="col col-center">
         <div class="form-group">
              <label for="sel1">Choose a Category:</label>
              <select class="form-control" id="sel1">
                <option onclick="filterPerCategory('all');">All Categories </option>
                  {% for category in all_category %}
                <option onclick="filterPerCategory('{{ category.name }}');">{{ category.name }} </option>
                  {% endfor %}
              </select>
        </div>
    </div>
</div>
<div class="row">
    {% for pictures in all_picture %}
        {% for item in pictures %}

            <div class="col-2 {{ item.category }} category" id="category" align="center">
                  <h8>{{ item.name }}</h8>
                    <br/>
                  <a href="{% url 'portfolio:carouselv2' item.id %}"><img class="img-thumbnail" src="{{ item.photo }}" alt="{{ item.name }}" width="200"></a>
            </div>
        {% endfor %}
        {% endfor %}

</div>
{% endblock content %}

templates/portfolio/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock title %}



{% block content %}
<div class="p-2">
    <h1>Welcome to my portfolio</h1>

    <a id="gallery">This is a test</a>
    <input class="btn btn-secondary" id="clickMe" type="button" value="clickme" onclick="changeValue();" />
</div>
{% endblock content %}

templates/portfolio/list.html
{% extends "base.html" %}
{% block title %}{% endblock title %}

{% block content %}
<main class="main">
<div class="container-fluid">
<table class="table table-bordered">
    <thead>
        <tr>
            <th>Item</th>
        </tr>
    </thead>
    <tbody>
    {% for picture in latest_picture_list %}
        <tr>
            <td><a href="{% url 'portfolio:picture' picture.id %}">{{ picture.name }}</a></td>
        </tr>
    {% endfor %}
    </tbody>
</table>
</div>
</main>
{% endblock content %}

templates/portfolio/mygallery.html
{% extends "base.html" %}
{% block title %}My Gallery{% endblock title %}

{% block content %}
<main class="main">

<table class="table table-bordered">
    <thead>
        <tr>
            <th>Item</th>
        </tr>
    </thead>
 <!--   <tbody>
    {% for item in all_picture %}
        <tr>
            <td>{{ item.name }}</td>
        </tr>
    {% endfor %}
    </tbody>
    -->
    <div class="row">
    {% for item in all_picture %}
    <div class="col">
          <h8>{{ item.name }}</h8>
            <br/>
          <a href="{% url 'portfolio:picture' item.id %}"><img class="img-thumbnail" src="{{ item.photo }}" alt="{{ item.name }}" width="200"></a>
    </div>

    {% endfor %}
    </div>

</table>

{% if all_picture %}
<table>
    <tr class="pagination">
        {% if all_picture.has_previous %}
            <td><a href="?page{{ all_picture.previous_page_number }}">Previous</a></td>
        {% endif %}
                <td class="">
                    <span>{{ all_picture.number }} of {{ all_picture.paginator.num_pages }}.</span>
                </td>
        {% if all_picture.has_next %}
            <td><a href="?page={{ all_picture.next_page_number }}">Next</a></td>
        {% endif %}

        </tr>
    {% endif %}
</table>
</main>
{% endblock content %}

templates/portfolio/picture.html
{% extends "base.html" %}
{% block title %}{{ picture.name }}{% endblock title %}

{% block content %}

<h1>{{ picture.name }}</h1>
<div class="container-fluid">
<p>Type: {{ picture.category }}</p>
<img class="img-fluid" src="{{ picture.photo }}" alt="{{ picture.name }}" width="50%" height="auto">
</div>

{% endblock content %}

templates/portfolio/send_dictionary.html
{% extends "base.html" %}
{% block title %}{{ picture.name }}{% endblock title %}

{% block content %}

    <div style="width: 40%; 
    border: 1px solid black; 
    background-color: lightcyan; 
    font-family: Helvetica, sans-serif;"> 
        <div style="margin: 5%;"> 
            <h1> 
                <u>Dictionary Data</u> 
            </h1> 
            <h2> 
                <u>All Data</u> 
            </h2> 
            <h4 id='alldata'></h4><br> 
            <h2> 
                <u>Neat Data</u> 
            </h2> 
            <h4 id='neatdata'></h4> 
        </div> 
    </div> 
</body> 
</html> 
<script> 
    var data = JSON.parse("{{data|escapejs}}"); 
    var dataNode = document.getElementById('alldata'); 
    dataNode.innerHTML+="{{data|escapejs}}"; 
    dataNode = document.getElementById('neatdata'); 
    for(var x in data){ 
        dataNode.innerHTML+=x+' : '+data[x]+'<br><br>'; 
    } 
</script>

{% endblock content %}

templates/portfolio/upload_picture.html
{% extends "base.html" %}
{% block title %}Upload Image{% endblock title %}

{% block content %}

<div class="p-1"></div>

<div class="col-4" xmlns="http://www.w3.org/1999/html">
  <h4 class="mb-4">Upload Picture</h4>
</div>

<div class="col-6" xmlns="http://www.w3.org/1999/html">
<form method="post" enctype="multipart/form-data">
{% csrf_token %}

{% for field in form %}
  <!--  <div class="fieldWrapper">-->
        <div class="form-group row p-1 m-1">
          <!--<div class="col-md-6 mb-3">-->
        {{ field.errors }}
         <a class="col-sm-2">{{ field.label_tag }}</a>
            <div class="col-sm-4">
                {{ field }}
            </div>
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
         <!-- </div>-->
        </div>
{% endfor %}
    <div class="row p-1 m-1 text-center">
        <button type="submit" class="btn btn-light btn-primary btn-block">Submit</button>
    </div>

</form>
</div>
{% endblock content %}