blog/urls.py
from . import views
from django.urls import path


app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='list_post'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

hopops/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_profile/', include('user_profile.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += path('', include('portfolio.urls')),

blog/models.py
from django.db import models
from django.contrib.auth.models import User


STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Post(models.Model):
    title = models.CharField(max_length=200, unique=True)
    slug = models.SlugField(max_length=200, unique=True)
    author = models.ForeignKey(User, on_delete= models.CASCADE,related_name='blog_posts')
    updated_on = models.DateTimeField(auto_now= True)
    content = models.TextField()
    created_on = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=STATUS, default=0)

    class Meta:
        ordering = ['-created_on']

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render

# Create your views here.
from django.views import generic
from .models import Post


class PostList(generic.ListView):
    queryset = Post.objects.filter(status=1).order_by('-created_on')
    template_name = 'blog/list_blog.html'


class PostDetail(generic.DetailView):
    model = Post
    template_name = 'blog/post_detail.html'

templates/blog/list_blog.html
{% extends "base.html" %} 
{% load static %}
{% block content %}


<header class="masthead">
    <div class="overlay"></div>
    <div class="container">
        <div class="row">
           <!-- <div class=" col-md-8 col-md-10 mx-auto">
                <div class="site-heading">
                    <h3 class=" site-heading my-4 mt-3 text-white"> Welcome to my awesome Blog </h3>
                    <p class="text-light">We Love Django As much as you do..! &nbsp
                    </p>
                </div>
            </div>-->
        </div>
    </div>
</header>
<div class="container">
    <div class="md-2 pt-4">
        <div class="row">
            <!-- Blog Entries Column -->
            <div class="col-md-8 mb-1 mt-2">
                {% for post in post_list %}
                <div class="card mb-4">
                    <div class="card-body">
                        <h2 class="card-title">{{ post.title }}</h2>
                        <p class="card-text text-muted h6">{{ post.author }} | {{ post.created_on}} </p>
                        <p class="card-text">{{post.content|slice:":100" }}</p>
                        <a href="{% url 'blog:post_detail' post.slug  %}" class="btn btn-primary">Read More &rarr;</a>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{%endblock%}

templates/blog/post_detail.html
{% extends 'base.html' %}
{% load static %}

{% block content %}



<div class="container">
  <div class="row">
    <div class="col-md-8 card mb-4  mt-4 left  top">
      <div class="card-body">
        <h1>{% block title %} {{ object.title }} {% endblock title %}</h1>
        <p class=" text-muted">{{ post.author }} | {{ post.created_on }}</p>
        <p class="card-text ">{{ object.content | safe }}</p>
      </div>
    </div>
  </div>
</div>

{% endblock content %}