blog/urls.py
from . import views
from django.urls import path


app_name = 'blog'

urlpatterns = [
    path('', views.PostList.as_view(), name='list_post'),
    path('<slug:slug>/', views.PostDetail.as_view(), name='post_detail'),
]

hopops/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user_profile/', include('user_profile.urls')),
    path('portfolio/', include('portfolio.urls')),
    path('blog/', include('blog.urls')),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

#urlpatterns += path('', include('portfolio.urls')),

portfolio/urls.py
from django.urls import path, re_path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from rest_framework import routers

from . import views

app_name = 'portfolio'

router = routers.DefaultRouter()
router.register(r'pictures', views.pictures, 'pictures')


urlpatterns = [
    path('list', views.list.as_view(), name="list"),
    path('gallery', views.gallery, name="gallery"),
    path('galleryv2', views.galleryv2, name="galleryv2"),
    path('mygallery', views.mygallery, name="mygallery"),
    path('<int:pk>', views.picture.as_view(), name="picture"),
    path('carousel/<int:picture_id>', views.carousel, name="carousel"),
    path('carouselv2/<int:picture_id>', views.carouselv2, name="carouselv2"),
    path('upload_image', views.upload_picture, name="upload_image"),
    path('test', views.get_photo, name="get_photo"),
 #   path('api/all_picture', views.all_picture, name="api_all_picture"),
    path('api/', include(router.urls)),
    path('', views.index, name="index"),
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static('/', document_root=settings.MEDIA_ROOT)

user_profile/urls.py
from django.urls import path
from django.conf import settings

from . import views

app_name = 'user_profile'

urlpatterns = [
    path('register', views.register, name="register"),
    path('logout', views.logout_user, name="logout"),
    path('login', views.login_user, name="login"),
    path('edit_user', views.edit_user, name="edit_user"),
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <!-- My stylesheet -->
    <link rel="stylesheet" href="{% static 'style.css' %}" />


    <title>{% block title %}{% endblock title %}</title>
</head>

<body>

<div class="mytop">
<header class="container-fluid">
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top nav">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-collapse"
          aria-controls="navbar-collapse" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
    </button>
  <div class="collapse navbar-collapse" id="navbar-collapse">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'portfolio:index' %}">Home <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'blog:list_post' %}">Blog</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'portfolio:gallery' %}">Gallery</a>
      </li>
      </ul>
      {% if user.is_authenticated %}
          <li class="nav-item">
          <a class="btn btn-secondary nav-link" href="{% url 'portfolio:upload_image' %}" >Upload</a>
          </li>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">{{ user.get_username }}</a>
           <div class="dropdown-menu" aria-labelledby="dropdown01">
          {% if request.user.is_staff %}
            <a class="dropdown-item" href="{% url 'admin:index' %}">Admin</a>
          {% endif %}
          <a class="dropdown-item" href="{% url 'portfolio:mygallery' %}">My Gallery</a>
          <a class="dropdown-item" href="{% url 'user_profile:edit_user' %}">My Profile</a>
          <a class="dropdown-item" href="{% url 'user_profile:logout' %}">Logout</a>
        </div>
      </li>
      </ul>
      {% else %}
    <form class="form-inline">
      <a class="btn btn-secondary" href="{% url 'user_profile:login' %}" >Login</a>
    </form>
    {% endif %}
  </div>

</nav>
</header>

</div>

<main>

  {% block content %}

  {% endblock content %}
</main>

<!-- Footer -->
<footer class="page-footer font-small blue pt-4 bg-light border">

  <!-- Footer Links -->
  <div class="container-fluid text-center text-md-left">

    <!-- Grid row -->
    <div class="row">

      <!-- Grid column -->
      <div class="col-md-6 mt-md-0 mt-3">

        <!-- Content -->
        <h5 class="text-uppercase">About</h5>
        <p>Here you can use rows and columns to organize your footer content.</p>

      </div>
      <!-- Grid column -->

      <hr class="clearfix w-100 d-md-none pb-3">

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">
      </div>
      <!-- Grid column -->

      <!-- Grid column -->
      <div class="col-md-3 mb-md-0 mb-3">

        <!-- Links -->
        <h5 class="text-uppercase">Social Media</h5>

        <ul class="list-unstyled">
          <li>
            <a href="https://www.instagram.com/hopops8/">Instagram</a>
          </li>
          <li>
            <a href="#!">Twitter</a>
          </li>
          <li>
            <a href="https://www.facebook.com">Facebook</a>
          </li>
          <li>
            <a href="https://www.linkedin.com/in/franck-collen/">Linkedin</a>
          </li>
        </ul>

      </div>
      <!-- Grid column -->

    </div>
    <!-- Grid row -->

  </div>
  <!-- Footer Links -->

  <!-- Copyright -->
  <div class="footer-copyright text-center py-3">© 2020 Copyright:
    <a href="https://franck-collen.com/"> franck-collen.com</a>
  </div>
  <!-- Copyright -->

</footer>
<!-- Footer -->

</body>

<!-- Utils js libs -->
<script src="{% static 'utils.js' %}"></script>
<!-- jQuery and JS bundle w/ Popper.js -->

<!-- CSS -->

<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>

</html>